[build]
builder = "NIXPACKS"
watchPatterns = ["package.json"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y wget gnupg ca-certificates procps libxss1 libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libpango-1.0-0 libpangocairo-1.0-0 libcairo2 libatspi2.0-0"
] 